### ISSUE TITLE
Upload to `rapidsai` directly (skip `rapidsai-nightly`?)

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/rapids-build-backend#48]
Given this just makes stable releases and pushes directly to PyPI ( https://github.com/rapidsai/rapids-build-backend/pull/47 ), it may make sense to do the same and push directly to `rapidsai` (skipping `rapidsai-nightly`)

**Comment by jameslamb** [comment]
I support this at this stage in its development. We aren't publishing nightlies / pre-releases and I expect the pace of new releases (and therefore manual ops work to publish to the `rapidsai` channel) to be pretty low.

**Comment by jakirkham** [comment]
In offline discussion with OPS, sounds like this should now work with a new release. Testing in PR: https://github.com/rapidsai/rapids-build-backend/pull/49

**Comment by jakirkham** [comment]
Looks like this uploaded to `rapidsai`:

<img width="1840" alt="Screenshot 2024-07-09 at 12 46 32 PM" src="https://github.com/rapidsai/rapids-build-backend/assets/3019665/3122330a-7a95-4faa-a182-f13cd1ae372b">

https://anaconda.org/rapidsai/rapids-build-backend/files?version=0.3.2
